routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['as' => 'front.', 'namespace' => 'Front'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/estatisticas', 'HomeController@estatisticas')->name('estatisticas');
    Route::get('solicitacao/nova', 'SolicitacaoController@nova')->name('solicitacao.nova');
    Route::post('solicitacao/nova', 'SolicitacaoController@storerNova')->name('solicitacao.storeNova');
    Route::get('solicitacao/consulta', 'SolicitacaoController@consulta')->name('solicitacao.consulta');
    Route::post('solicitacao/consulta', 'SolicitacaoController@consultaProtocolo')->name('solicitacao.consulta');

    Route::prefix('solicitante')->name('solicitante.')->group(function () {
        Route::get('/novo', 'SolicitanteController@index')->name('novo');
        Route::resource('/', 'SolicitanteController', ['except' => ['edit', 'show', 'update', 'destroy', 'create']]);

        Route::group(['namespace' => 'Auth'], function () {
            Route::get('login', 'LoginController@showLoginForm')->name('login');
            Route::post('login', 'LoginController@login')->name('login');
            Route::post('logout', 'LoginController@logout')->name('logout');
        });
    });

    Route::group(['middleware' => 'auth:solicitante'], function () {
        Route::post('solicitacao/recurso', 'SolicitacaoController@recurso')->name('solicitacao.recurso');
        Route::resource('solicitacao', 'SolicitacaoController', ['except' => ['edit', 'update', 'destroy']]);

        Route::get('usuario/ver', 'SolicitanteController@create')->name('usuario.ver');
        Route::get('usuario/alterar_senha', 'SolicitanteController@alteraSenha')->name('usuario.altera-senha');
        Route::put('usuario/alterar_senha', 'SolicitanteController@updateSenha')->name('usuario.update-senha');
        Route::resource('usuario', 'SolicitanteController', ['except' => ['show', 'destroy', 'create', 'store']]);
    });

    Route::resource('pagina', 'PaginaController');
});


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'auth'], function () {
    Route::get('sic_fisico/remove-arquivo/{id}/{field}', 'SicFisicoController@destroyFile')->name('sic_fisico.destroy-file');
    Route::resource('sic_fisico', 'SicFisicoController');

    Route::resource('/', 'DashboardController');
    Route::resource('orgao', 'OrgaoController', ['except' => []]);
    Route::resource('movimentacao', 'MovimentacaoController', ['except' => []]);
    Route::resource('resposta', 'RespostaController', ['except' => []]);
    Route::resource('pagina', 'PaginaController', ['except' => []]);
    Route::resource('solicitacao', 'SolicitacaoController', ['except' => []]);
    Route::resource('solicitante', 'SolicitanteController', ['except' => []]);


    Route::get('resposta/homologar/{solicitacao_id}/{resposta_id}', 'RespostaController@homologar')->middleware(['can:user-central'])->name('resposta.homologar');

    Route::post('solicitacao/prorrogar/{id}', 'SolicitacaoController@prorrogar')->middleware(['can:user-central'])->name('solicitacao.prorrogar');
    Route::get('solicitacao/receber/{id}', 'SolicitacaoController@receber')->name('solicitacao.receber');
    Route::get('solicitacao/receber_diligencia/{id}', 'SolicitacaoController@receber_diligencia')->name('solicitacao.receber_diligencia');
    Route::post('solicitacao/responder/{id}', 'SolicitacaoController@responder')->name('solicitacao.responder');
    Route::post('solicitacao/responder_diligencia/{id}', 'SolicitacaoController@responder_diligencia')->name('solicitacao.responder_diligencia');
    Route::post('solicitacao/tramitar/{id}', 'SolicitacaoController@tramitar')->name('solicitacao.tramitar');
    Route::post('solicitacao/diligencia/{id}', 'SolicitacaoController@diligencia')->name('solicitacao.diligencia');
    Route::get('solicitacao/diligencia/{id}', 'SolicitacaoController@ver_diligencia')->name('solicitacao.ver_diligencia');

    Route::middleware(['can:user-admin'])->group(function () {
        Route::resource('perfil', 'PerfilController', ['except' => ['show']]);
        Route::resource('situacao', 'SituacaoController', ['except' => ['show']]);
        Route::resource('escolaridade', 'EscolaridadeController', ['except' => ['show']]);
        Route::resource('usuarios', 'UsersController', ['except' => []]);
        Route::resource('tipo_retorno', 'TipoRetornoController', ['except' => ['show']]);
        Route::resource('tipo_solicitacao', 'TipoSolicitacaoController', ['except' => ['show']]);
        Route::resource('tipo_movimentacao', 'TipoMovimentacaoController', ['except' => ['show']]);
        Route::resource('faixa-etaria', 'FaixaEtariaController', ['except' => ['show']]);
        Route::resource('tipo_telefone', 'TipoTelefonesController', ['except' => ['show']]);
        Route::resource('config_entidade', 'ConfiguracaoEntidadeController', ['except' => ['show', 'destroy']]);
        Route::resource('config_lai', 'ConfiguracaoLaiController', ['except' => ['show', 'destroy']]);
    });
});

Route::group(['namespace' => 'Auth'], function () {
    //Login
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login');
    Route::post('logout', 'LoginController@logout')->name('logout');
    // Registration Routes...
    //Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    //Route::post('register', 'RegisterController@register');
    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');
});

resources/views/layouts/poco/menu-footer.blade.php
<div class="footer">
    <div class="container">
        <div class="row">
            <!-- About -->
            <div class="col-md-3 md-margin-bottom-40">
                <section>
                    <h3 class="widget-title">Institucional</h3>
                    <ul id="menu-institucional-rodape" class="menu">
                        <li><a href="{{ env('URL_INSTITUCIONAL', '#') }}" target="_blank">Poder Executivo</a></li>
                        <li><a href="{{ env('URL_INSTITUCIONAL', '#') }}/controladoria/" target="_blank">Controladoria</a></li>
                        <li><a href="{{ env('URL_INSTITUCIONAL', '#') }}/procuradoria/" target="_blank">Procuradoria</a></li>
                    </ul>
                </section>
                <section>
                    <h3 class="widget-title">Secretarias</h3>
                    <ul id="menu-secretarias-rodape" class="menu">
                        <li>
                            <a href="{{ env('URL_INSTITUCIONAL', '#') }}/secretaria-de-administracao/" target="_blank">Administração</a>
                        </li>
                        <li>
                            <a href="{{ env('URL_INSTITUCIONAL', '#') }}/secretaria-de-agricultura-e-meio-ambiente/" target="_blank">Agricultura
                                e Meio Ambiente</a></li>
                        <li>
                            <a href="{{ env('URL_INSTITUCIONAL', '#') }}/secretaria-de-assistencia-social/" target="_blank">Assistência
                                Social</a></li>
                        <li>
                            <a href="{{ env('URL_INSTITUCIONAL', '#') }}/secretaria-de-cultura-e-esportes/" target="_blank">Cultura
                                e Esportes</a></li>
                        <li>
                            <a href="{{ env('URL_INSTITUCIONAL', '#') }}/secretaria-de-educacao/" target="_blank">Educação</a>
                        </li>
                        <li>
                            <a href="{{ env('URL_INSTITUCIONAL', '#') }}/secretaria-de-financas/" target="_blank">Finanças</a>
                        </li>
                        <li>
                            <a href="{{ env('URL_INSTITUCIONAL', '#') }}/secretaria-de-obras-saneamento-e-urbanismo/" target="_blank">Obras,
                                Saneamento e Urbanismo</a></li>
                        <li>
                            <a href="{{ env('URL_INSTITUCIONAL', '#') }}/secretaria-de-saude/" target="_blank">Saúde</a>
                        </li>
                        <li>
                            <a href="{{ env('URL_INSTITUCIONAL', '#') }}/secretaria-de-transporte-e-transito/" target="_blank">Transporte
                                e Trânsito</a></li>
                    </ul>

                </section>
            </div><!--/col-md-3-->
            <!-- End About -->

            <!-- Latest -->
            <div class="col-md-3 md-margin-bottom-40">
                <section>
                    <h3 class="widget-title">Transparência</h3>
                    <ul>
                        <li><a title="Demonstrativos" href="{{ env('URL_TRANSPARENCIA', '#') }}/demonstrativos" target="_blank">Demonstrativos</a></li>
                        <li><a title="LRF - Lei de Responsabilidade Fiscal" href="{{ env('URL_TRANSPARENCIA', '#') }}/lrf" target="_blank">LRF - Lei de
                                Responsabilidade Fiscal</a></li>
                        <li><a title="Receitas" href="{{ env('URL_RECEITAS', '#') }}" target="_blank">Receitas</a></li>
                        <li><a title="Despesas" href="{{ env('URL_DESPESAS', '#') }}" target="_blank">Despesas</a></li>
                        <li><a title="Contratos" href="{{ env('URL_TRANSPARENCIA', '#') }}/contrato" target="_blank">Contratos</a></li>
                        <li><a title="Convênios" href="http://www.portaldatransparencia.gov.br/convenios/ConveniosLista.asp?UF=al&amp;CodMunicipio=2843" target="_blank">Convênios</a></li>
                        <li><a title="Licitações" href="{{ env('URL_TRANSPARENCIA', '#') }}/licitacao" target="_blank">Licitações</a></li>
                        <li><a title="Orçamento" href="{{ env('URL_TRANSPARENCIA', '#') }}/orcamento" target="_blank">Orçamento</a></li>
                        <li><a title="Servidores" href="{{ env('URL_TRANSPARENCIA', '#') }}/servidores">Servidores</a></li>
                        <li><a title="Legislação" href="{{ env('URL_TRANSPARENCIA', '#') }}/legislacao" target="_blank">Legislação</a></li>
                    </ul>
                </section>
            </div><!--/col-md-3-->
            <!-- End Latest -->

            <!-- Link List -->
            <div class="col-md-3 md-margin-bottom-40">
                <section>
                    <h3 class="widget-title">Serviços</h3>
                    <ul>
                        <li><a href="{{ env('URL_INSTITUCIONAL', '#') }}" target="_blank">Nota Fiscal Eletrônica</a></li>
                        <li><a href="{{ env('URL_INSTITUCIONAL', '#') }}" target="_blank">2º Via de Tributos</a></li>
                        <li><a href="{{ env('URL_INSTITUCIONAL', '#') }}" target="_blank">Agenda de Coleta de Lixo</a></li>
                    </ul>
                </section>
            </div><!--/col-md-3-->
            <!-- End Link List -->

            <!-- Address -->
            <div class="col-md-3 md-margin-bottom-40">
                <img src="{{ env('URL_TRANSPARENCIA', '#') }}/storage/configuracao/brasao-poco-3-1510689042.png" alt="Prefeitura Municipal de Poço das Trincheiras" class="img-responsive brasao">
                <div class="informacoes-contato">
                    <p>
                        <i class="fa fa-map-marker"></i>
                        Praça Leopoldo Wanderley, nº 91, Centro - Poço das Trincheiras - AL - 57.510-000
                    </p>
                    <p>
                        <i class="fa fa-envelope"></i>
                        <a href="mailto:pocodastrincheiras@hotmail.com"> pocodastrincheiras@hotmail.com</a>
                    </p>
                    <p><i class="fa fa-phone"></i> (82) 3626-1151 / 3626-1296</p>
                </div>
            </div><!--/col-md-3-->
            <!-- End Address -->
        </div>
    </div>
</div>

resources/views/layouts/poco/menu-header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            @if(auth()->guard('solicitante')->check())
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/') }}"><i class="fa fa-home"></i> Início</a></li>
                    <li><a href="{{ route('front.solicitacao.index') }}"><i class="fa fa-file-text-o"></i> Minhas
                            Solicitações</a></li>
                    <li><a href="{{ route('front.solicitacao.create') }}"><i class="fa fa-plus"></i> Nova
                            Solicitação</a></li>
                    <li><a href="{{ route('front.usuario.ver') }}"><i class="fa fa-user"></i> Meu Perfil</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#"
                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="fa fa-sign-out"></i> Sair </a>
                        <form id="logout-form" action="{{ route('front.solicitante.logout') }}" method="POST"
                              style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </li>
                </ul>
            @else
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/') }}">Início</a></li>
                    <li><a href="{{ env('URL_INSTITUCIONAL') }}">Institucional</a></li>
                    <li><a href="{{ env('URL_TRANSPARENCIA') }}">Portal da Transparência</a></li>
                    <li><a href="{{ route('front.estatisticas') }}">Estatísticas</a></li>
                    {{--@foreach($paginas as $p)--}}
                    {{--<li><a href="{{ route('front.pagina.show', $p->slug) }}">{{ $p->nome }}</a></li>--}}
                    {{--@endforeach--}}
                </ul>
            @endif
        </div>

    </div>
</nav>